sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    bucket-name: java-web-mu
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    access-key-id: ${OSS_ACCESS_KEY_ID}
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: ${WX_APP_ID}
    secret: ${WX_APP_SECRET}
